services:
  docling:
    image: ghcr.io/docling-project/docling-serve-cu124
    container_name: docling-serve
    ports:
      - 5001:5001
    user: root
    environment:
      - DOCLING_SERVE_ENABLE_UI=true
    command: >
      sh -c "dnf install -y epel-release && 
         dnf install -y https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm && 
         dnf install -y ffmpeg && 
         pip install openai-whisper && 
         exec python -m docling_serve run"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
