quarkus:
  langchain4j:
    mcp:
#      filesystem:
#        transport-type: stdio
#        command: npm,exec,@modelcontextprotocol/server-filesystem@0.6.2,playground
#        log-requests: true
#        log-responses: true

    easy-rag:
      path: src/main/resources/easy-rag-catalog
# To persist the RAG
#      reuse-embeddings:
#        enabled: true
    timeout: 60s
    ollama:
      chat-model:
        model-name: granite3.3:8b
        temperature: 0.1
        top-k: 10
        top-p: 0.95
        format: json
      log-requests: false
      log-responses: false

# Docling Stuff

#  rest-client:
#    document-conversion-api:
#      url: http://localhost:5001
#      read-timeout: 600000
#  docling:
#    log-requests: true
#    log-responses: true
#    base-url: http://localhost:5001

# Enable comprehensive logging
  log:
    level:
      dev.wad: DEBUG
      io.quarkiverse.langchain4j: DEBUG
      dev.langchain4j: DEBUG
      ROOT: INFO
    console:
      enable: true
      format: "%d{HH:mm:ss} %-5p [%c{2.}] (%t) %s%e%n"